@hostname=http://localhost

@port=4001

@host={{hostname}}:{{port}}


###
GET {{host}}/

###
GET {{host}}/query?nombre=fredo&apellido=Noriega

###
GET {{host}}/courses

###
GET {{host}}/courses/2
###
GET {{host}}/courses/5